const languages = [
  { label: 'Afrikaanca' },
  { label: 'Almanca' },
  { label: 'Arapça' },
  { label: 'Bengalce' },
  { label: 'Çince' },
  { label: 'Endonezce' },
  { label: 'Fransızca' },
  { label: 'Hintçe' },
  { label: 'İngilizce' },
  { label: 'İspanyolca' },
  { label: 'İtalyanca' },
  { label: 'Japonca' },
  { label: 'Korece' },
  { label: 'Malayca' },
  { label: 'Marathice' },
  { label: 'Peştuca' },
  { label: 'Pencapça' },
  { label: 'Portekizce' },
  { label: 'Rusça' },
  { label: 'Svahili' },
  { label: 'Tamilce' },
  { label: 'Teluguce' },
  { label: 'Türkçe' },
  { label: 'Ukraynaca' },
  { label: 'Urduca' },
  { label: 'Vietnamca' },
  { label: 'İşaret Dili' }
];

export default languages;
